# Generated by Django 4.1.3 on 2023-06-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('doctor', models.CharField(max_length=25)),
                ('date', models.CharField(max_length=5)),
            ],
        ),
    ]
